train_data_dir: "/Users/therold/Uni/master-thesis/datasets/wav_segmented/training.csv"
validation_data_dir: "/Users/therold/Uni/master-thesis/datasets/wav_segmented/validation.csv"
test_data_dir: "/extra/tom/validation/segmented/testing.csv"

batch_size: 32
learning_rate: 0.001
max_train_steps: 100000

num_train_files: 2187144
num_test_files: 546788

# mel images
image_width: 121 # 1 sec mono audio; automatically calculated: segement_length * 121px
image_height: 40
image_depth: 3

# full size spectrograms
#image_width: 100 # 1 sec mono audio; automatically calculated: segement_length * 100px
#image_height: 506
#image_depth: 1

segment_length: 5 # sec

label_names: ["EN", "DE", "FR", "ES"]
num_classes: 4



