train_data_dir: "/Users/therold/Uni/master-thesis/datasets/wav_segmented/training.csv"
validation_data_dir: "/Users/therold/Uni/master-thesis/datasets/wav_segmented/testing.csv"
test_data_dir: "/extra/tom/validation/segmented/testing.csv"

batch_size: 32
learning_rate: 0.001
max_train_steps: 100000

num_train_files: 52604
num_test_files: 13152

image_width: 1207 # 10 sec mono audio
image_height: 60
image_depth: 1

label_names: ["EN", "DE", "FR", "ES"]
num_classes: 4



