train_data_dir: "/extra/tom/news/segmented/training.csv"
validation_data_dir: "/extra/tom/news/segmented/testing.csv"
test_data_dir: "/extra/tom/validation/segmented/testing.csv"

batch_size: 32
learning_rate: 0.001
max_train_steps: 100000

num_train_files: 144000
# num_test_files: 33000
num_test_files: 36000

image_width: 1207 # 10 sec mono audio
image_height: 40
image_depth: 1

label_names: ["EN", "DE", "FR", "ES"]
num_classes: 4



